### ISSUE TITLE
OAuth token refresh error

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-aspects#152]
When a token expires and tries to get refreshed Superset throws errors until the user logs out and back in:

![Screenshot 2023-07-06 at 3 33 59 PM](https://github.com/openedx/tutor-contrib-aspects/assets/112640379/f99e439f-5f08-45b8-9534-d64f1f848103)

```
2023-07-06 15:26:23 2023-07-06 19:26:23,404:ERROR:superset.views.base:invalid_grant: 
2023-07-06 15:26:23 Traceback (most recent call last):
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
2023-07-06 15:26:23     rv = self.dispatch_request()
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
2023-07-06 15:26:23     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 89, in wraps
2023-07-06 15:26:23     return f(self, *args, **kwargs)
2023-07-06 15:26:23   File "/app/superset/views/base_api.py", line 113, in wraps
2023-07-06 15:26:23     raise ex
2023-07-06 15:26:23   File "/app/superset/views/base_api.py", line 110, in wraps
2023-07-06 15:26:23     duration, response = time_function(f, self, *args, **kwargs)
2023-07-06 15:26:23   File "/app/superset/utils/core.py", line 1524, in time_function
2023-07-06 15:26:23     response = func(*args, **kwargs)
2023-07-06 15:26:23   File "/app/superset/utils/log.py", line 245, in wrapper
2023-07-06 15:26:23     value = f(*args, **kwargs)
2023-07-06 15:26:23   File "/app/superset/charts/data/api.py", line 244, in data
2023-07-06 15:26:23     return self._get_data_response(
2023-07-06 15:26:23   File "/app/superset/charts/data/api.py", line 390, in _get_data_response
2023-07-06 15:26:23     result = command.run(force_cached=force_cached)
2023-07-06 15:26:23   File "/app/superset/charts/data/commands/get_data_command.py", line 43, in run
2023-07-06 15:26:23     payload = self._query_context.get_payload(
2023-07-06 15:26:23   File "/app/superset/common/query_context.py", line 100, in get_payload
2023-07-06 15:26:23     return self._processor.get_payload(cache_query_context, force_cached)
2023-07-06 15:26:23   File "/app/superset/common/query_context_processor.py", line 386, in get_payload
2023-07-06 15:26:23     query_results = [
2023-07-06 15:26:23   File "/app/superset/common/query_context_processor.py", line 387, in <listcomp>
2023-07-06 15:26:23     get_query_results(
2023-07-06 15:26:23   File "/app/superset/common/query_actions.py", line 200, in get_query_results
2023-07-06 15:26:23     return result_func(query_context, query_obj, force_cached)
2023-07-06 15:26:23   File "/app/superset/common/query_actions.py", line 104, in _get_full
2023-07-06 15:26:23     payload = query_context.get_df_payload(query_obj, force_cached=force_cached)
2023-07-06 15:26:23   File "/app/superset/common/query_context.py", line 121, in get_df_payload
2023-07-06 15:26:23     return self._processor.get_df_payload(query_obj, force_cached)
2023-07-06 15:26:23   File "/app/superset/common/query_context_processor.py", line 100, in get_df_payload
2023-07-06 15:26:23     cache_key = self.query_cache_key(query_obj)
2023-07-06 15:26:23   File "/app/superset/common/query_context_processor.py", line 163, in query_cache_key
2023-07-06 15:26:23     extra_cache_keys = datasource.get_extra_cache_keys(query_obj.to_dict())
2023-07-06 15:26:23   File "/app/superset/connectors/sqla/models.py", line 2092, in get_extra_cache_keys
2023-07-06 15:26:23     sqla_query = self.get_sqla_query(**query_obj)
2023-07-06 15:26:23   File "/app/superset/connectors/sqla/models.py", line 1630, in get_sqla_query
2023-07-06 15:26:23     where_clause_and += self.get_sqla_row_level_filters(template_processor)
2023-07-06 15:26:23   File "/app/superset/connectors/sqla/models.py", line 1190, in get_sqla_row_level_filters
2023-07-06 15:26:23     f"({template_processor.process_template(filter_.clause)})"
2023-07-06 15:26:23   File "/app/superset/jinja_context.py", line 474, in process_template
2023-07-06 15:26:23     return template.render(context)
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
2023-07-06 15:26:23     self.environment.handle_exception()
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
2023-07-06 15:26:23     raise rewrite_traceback_stack(source=source)
2023-07-06 15:26:23   File "<template>", line 1, in top-level template code
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/jinja2/sandbox.py", line 393, in call
2023-07-06 15:26:23     return __context.call(__obj, *args, **kwargs)
2023-07-06 15:26:23   File "/app/pythonpath/openedx_jinja_filters.py", line 32, in can_view_courses
2023-07-06 15:26:23     courses = security_manager.get_courses(username)
2023-07-06 15:26:23   File "/app/superset/utils/memoized.py", line 50, in __call__
2023-07-06 15:26:23     value = self.func(*args, **kwargs)
2023-07-06 15:26:23   File "/app/pythonpath/openedx_sso_security_manager.py", line 130, in get_courses
2023-07-06 15:26:23     response = oauth_remote.get(url, token=token).json()
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/authlib/integrations/base_client/sync_app.py", line 29, in get
2023-07-06 15:26:23     return self.request('GET', url, **kwargs)
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/authlib/integrations/base_client/sync_app.py", line 289, in request
2023-07-06 15:26:23     return self._send_token_request(session, method, url, token, kwargs)
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/authlib/integrations/base_client/sync_app.py", line 89, in _send_token_request
2023-07-06 15:26:23     return session.request(method, url, **kwargs)
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/authlib/integrations/requests_client/oauth2_session.py", line 109, in request
2023-07-06 15:26:23     return super(OAuth2Session, self).request(
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 528, in request
2023-07-06 15:26:23     prep = self.prepare_request(req)
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 456, in prepare_request
2023-07-06 15:26:23     p.prepare(
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 320, in prepare
2023-07-06 15:26:23     self.prepare_auth(auth, url)
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 556, in prepare_auth
2023-07-06 15:26:23     r = auth(self)
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/authlib/integrations/requests_client/oauth2_session.py", line 24, in __call__
2023-07-06 15:26:23     self.ensure_active_token()
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/authlib/integrations/requests_client/oauth2_session.py", line 20, in ensure_active_token
2023-07-06 15:26:23     if self.client and not self.client.ensure_active_token(self.token):
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/authlib/oauth2/client.py", line 262, in ensure_active_token
2023-07-06 15:26:23     self.refresh_token(url, refresh_token=refresh_token)
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/authlib/oauth2/client.py", line 252, in refresh_token
2023-07-06 15:26:23     return self._refresh_token(
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/authlib/oauth2/client.py", line 373, in _refresh_token
2023-07-06 15:26:23     token = self.parse_response_token(resp)
2023-07-06 15:26:23   File "/usr/local/lib/python3.8/site-packages/authlib/oauth2/client.py", line 340, in parse_response_token
2023-07-06 15:26:23     raise self.oauth_error_class(
2023-07-06 15:26:23 authlib.integrations.base_client.errors.OAuthError: invalid_grant: 
```

**Comment by Ian2012** [comment]
- Store the token, expires-in, and refresh-token in the session
- Refresh token when needed
